# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(blank=True, max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('referer', models.URLField(blank=True)),
                ('user_agent', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
